# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
version: 2
before:
  hooks:
    - make test
    - cd tools && make cross-compile-lsp
builds:
  # Main Porch CLI
  - id: porch
    env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X github.com/matt-FFFFFF/porch.Version={{.Version}} -X github.com/matt-FFFFFF/porch.Commit={{.Commit}}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: "{{ .ProjectName }}"
    main: ./cmd/{{ .ProjectName }}

  # Porch HCL Language Server
  - id: porch-lsp
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: porch-lsp
    main: ./cmd/porch-lsp
    dir: ./tools/language-server
archives:
  - id: porch-cli
    builds: [porch]
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - formats: [zip]
        goos: windows
  - id: porch-lsp
    builds: [porch-lsp]
    formats: [tar.gz]
    name_template: "porch-lsp_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - formats: [zip]
        goos: windows
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
release:
  make_latest: true
  name_template: "Porch v{{ .Version }}"
  header: |
    ## Porch v{{ .Version }}

    This release includes both the Porch CLI and the Porch HCL Language Server.

    ### Porch CLI
    The main Porch command-line tool for workflow execution.

    ### Porch HCL Language Server
    A Language Server Protocol (LSP) implementation for `.porch.hcl` files that provides:
    - Syntax validation and real-time diagnostics
    - Auto-completion for blocks, attributes, and HCL functions
    - Hover documentation
    - Context-aware suggestions

    To use the language server with VSCode, install the Porch HCL extension from the marketplace or build it from source in the `tools/vscode-extension` directory.

  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
changelog:
  disable: false
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Doc updates"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other updates"
      order: 999
